[project]
name = "attn-visulizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "streamlit>=1.28.0",
    "plotly>=5.15.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
]
